ip='127.0.0.1'
port=8080

# data_dir structure:
# |- {book_id}
#    |- 1.txt
#    |- 2.txt
data_dir=''

# frontend_dir structure:
# |- index.html
# |- favicon.ico
# |- assets/
frontend_dir=''

server_data_dir='.'
